#+TITLE: Imperfect Information in Health Care Markets
#+AUTHOR: Christoph Schottmüller
#+Options: toc:nil H:2
#+Latex_Header: \usepackage{natbib}

* News
- Note that there is no exercise session on October 8 as it makes no sense to have an exercise session before the first lecture.

* Course material
The course plan as [[https://github.com/schottmueller/infohealthecon/files/2437665/plan.pdf][pdf]] on which you can also find a list of references.

The exercises are available in [[https://github.com/schottmueller/infohealthecon/files/2468024/ex.pdf][pdf]] and as [[https://github.com/schottmueller/infohealthecon/blob/master/exercises/ex.org][.org]] file.

Lecture slides will be posted here later on. You can find the source code creating the slides as Emacs org-mode files (".org") [[https://github.com/schottmueller/infohealthecon/tree/master/slides][here]].

- intro [[https://github.com/schottmueller/infohealthecon/files/2467992/intro.pdf][slides]]
- demand for insurance [[https://github.com/schottmueller/infohealthecon/files/2478815/insuranceDemand.pdf][slides]]

* Course setup 
In this course, we will analyze the consequences of information problems in health care markets and look for possible solutions to those problems on a theoretical basis. The theoretical analysis is at times supplemented with empirical evidence.

Students learn economic methods to analyze health care markets theoretically and also gain some insight in how to design empirical tests of the predictions of the theoretical models. 

The course consists of a lecture and an exercise session. Models, their solutions and implications as well as empirical evidence are presented in the lecture. In the exercise classes, solution to exercises are discussed. Students are expected to work on the exercises beforehand. Exercises consist mainly of calculation exercises using (variations of) models introduced in class but also discussion questions on specific applications. 

The exam will -- in style -- be similar to the questions of the exercise classes.

** Lecture times: 
- lecture: Thursday, 16:00-17:30 in 100/U1/HS VI
- exercise classes: Monday, 16:00-17:30 in 103/EG/0.211

** Textbooks
The course is not based on a single textbook. The majority of topics is covered in cite:zweifel2009health. cite:morrisey2008health covers also many of the discussed topics but has an (almost entirely) empirical approach. Detailed references are given in the schedule below.

* Detailed schedule
This is a plan and as every good plan it may be adjusted if necessary.
** Introduction
- economic approach (trade-offs, choice-preferences-utility maximization, uncertainty, models)
- tools (optimization, regression analysis and endogeneity)
** Imperfect information between patient and insurer
*** demand for insurance
- full coverage (ch. 3 cite:morrisey2008health)
- coverage choice (ch. 5.3.1 and 5.3.2 cite:zweifel2009health) 
- supplementary reading: ch. 6.3 cite:zweifel2009health
*** adverse selection
- fixed coverage 
- menus and distortions 
- premium risk, community rating and risk adjustment 
- main reading: p. 115-123 cite:einav2011selection, ch. 5.3.3-5.3.4 cite:zweifel2009health
- supplementary reading:  cite:rothschild1976equilibrium, cite:stiglitz1977monopoly, cite:lagerlof2018monopoly, ch. 7 cite:zweifel2009health, cite:behrend2007risk, cite:PMM2000755
*** advantageous selection and beyond
- advantageous selection: cite:hemenway1990propitious, cite:fang2008sources, cite:finkelstein2006multiple
- positive correlation test and its pitfalls: cite:boone2017networks

*** moral hazard
- RAND and Oregon health insurance experiments
- bunching estimators at the donut hole
- simple model of moral hazard
- reading: cite:einav2018moral, ch. 6.4.2 cite:zweifel2009health
- supplementary reading: cite:dave2009health, cite:aron2013rand
** Imperfect information between doctor and patient
*** supply induced demand
- reading: ch. 8 cite:zweifel2009health 
- supplementary reading: cite:fuchs1978supply,gruber1996physician, cite:krasnik1990changing
# (also slides Wambach)
*** models of doctor patient interaction
# (slides Wambach)
- strategic communication and the hippocratic oath cite:schottmueller2013cifd
*** credence good models
cite:wolinsky1993competition 
# (slides Wambach)
** Imperfect information between doctor and insurer (and patient)
*** credence good models with insurance
# (slides Wambach)
*** selective contracting and managed care
- consumer steering and competition: cite:boone2017networks

# *** doctor renumeration under a global budget 
# cite:benstetter2006treadmill
*** health care payment systems
cite:ma1997optimal 



bibliographystyle:chicago
bibliography:/home/christoph/stuff/bibliography/references.bib

