#+TITLE: Imperfect Information in Health Care Markets
#+AUTHOR: Christoph Schottmüller
#+Options: toc:nil H:2
#+Latex_Header: \usepackage{natbib}

* News
- The exam will take place on February 7, 15:30-16:30 in HSI. Register for the exam via KLIPS before January 10. A second exam date will be determined later.
- Note that there is no exercise session on October 8 as it makes no sense to have an exercise session before the first lecture.
- There is now a julia/jupyter notebook that can compute the resuls to some of the exercises of the first 3 weeks. The idea is the following: If you want to practice more, you can simply change the income or the utility function and redo the exercise with these new primitives. The code allows you to check whether your calculation were correct. The "course materials" section below explains how you can use the notebook. (It is unlikely that this notebook will be extended to cover exercises of the coming weeks as the material is not that easily amenable to a programming solution).

* Prerequisites and background
Several students asked for references for the prerequisites in terms of mathematics, statistics and microeconomics. For all of these areas there are literally hundreds of books titled "(Intermediate/Introductory) Microeconomics" or "Mathematics/Statistics for Business/Economics" and all of them cover more or less the same. For concreteness, I name "Intermediate Microeconomis" ("Grundzüge der Mikroökpnomik") by Hal Varian where chapters 1-5 are assumed to be known and chapter 12 is what we covered in the second lecture. For mathematics, "Essential Mathematics for Economic Analysis" by Sysdsæter, Hammond, Strøm and Carvajal may be useful. I am not familiar with statistics books but everything targeted at first semester business/economics students should be fine. 

If you want to take a less broad approach in catching up, the internet offers a variety of materials and formats (lecture notes, video tutorials on major online video platforms, interactive websites) that can be found with the usual search engines. For example, Wikipedia provides short definitions and explanations (and often links to more in depth material). 

* Course material
Please note that I do not use ILIAS. The course plan as [[https://github.com/schottmueller/infohealthecon/files/2437665/plan.pdf][pdf]] on which you can also find a list of references.

The exercises are available in [[https://github.com/schottmueller/infohealthecon/files/2632623/ex.pdf][pdf]] and as [[https://github.com/schottmueller/infohealthecon/blob/master/exercises/ex.org][.org]] file. [[https://github.com/schottmueller/infohealthecon/blob/master/exercises/exercisePlots.ipynb][Plots]] shown in the exercise session.

Lecture slides are posted here over the course of the term. You can find the source code creating the slides as Emacs org-mode files (".org") [[https://github.com/schottmueller/infohealthecon/tree/master/slides][here]].

- intro [[https://github.com/schottmueller/infohealthecon/files/2467992/intro.pdf][slides]]
- demand for insurance [[https://github.com/schottmueller/infohealthecon/files/2478815/insuranceDemand.pdf][slides]]
- (adverse) selection [[https://github.com/schottmueller/infohealthecon/files/2610321/adverseSelection.pdf][slides]], numerical [[https://github.com/schottmueller/infohealthecon/blob/master/julia/HealthInsuranceNoSingleCrossing.ipynb][example]] no single crossing

** Julia notebooks

To execute the code in the julia/jupyter notebooks you can either install Julia locally (it's free and open source but the installation is somewhat more complicated) or use juliabox to run it in your browser. I described the details for another purpose [[https://github.com/schottmueller/juliaForMicroTheory/blob/master/0.%20Why%2C%20what%20and%20how.ipynb][here]] (in case you are interested in understanding the code check [[https://github.com/schottmueller/juliaForMicroTheory][this]] repository). For the browser option, you follow these steps (you can follow the steps also on this [[https://www.dropbox.com/s/fqh4k9no3fd14s6/Screencast%20from%2011-01-2018%2004%3A11%3A15%20PM.webm?dl=0][screencast]]):

1. Go to [[https://github.com/schottmueller/infohealthecon]] and click on the green box saying "Clone or download". Choose "Download ZIP" and safe the folder on your hard drive. Unzip it in a folder of your choice.
2. Go to [[https://juliabox.com]] and login/register with a method of your choice.  Their free plan is more than enough for our purposes. After logging in, click "Launch", then click "Upload" and navigate to the unzipped folder on your hard drive. Inside this folder into "exercises" and select there "exercisePlots.ipynb". Click on the blue "Upload" box to confirm that you want to upload this file. Now you see the file "exercisePlots.ipynb" in your list of juliabox files. Click on it to start the file (it should open in a new tab).
3. To execute a cell, you click into it and then press Shift+Enter (that is you press Enter while keeping shift pressed).
4. The first time you log in, you need to execute the first cell (click in it and Shift+Enter) to install the necessary packages (they are not installed on your PC but on your juliabox account in the cloud). This can take almost a minute and produce strange looking output.

Note that the first time you run a cell it can take some time. It is fast afterwards.

Now you are ready. You can change the primitives of the problem, e.g. the utility functions or income, and executing the cell again will give you the results for the new problem.


* Course setup 
In this course, we will analyze the consequences of information problems in health care markets and look for possible solutions to those problems on a theoretical basis. The theoretical analysis is at times supplemented with empirical evidence.

Students learn economic methods to analyze health care markets theoretically and also gain some insight in how to design empirical tests of the predictions of the theoretical models. 

The course consists of a lecture and an exercise session. Models, their solutions and implications as well as empirical evidence are presented in the lecture. In the exercise classes, solution to exercises are discussed. Students are expected to work on the exercises beforehand. Exercises consist mainly of calculation exercises using (variations of) models introduced in class but also discussion questions on specific applications. 

The exam will -- in style -- be similar to the questions of the exercise classes.

** Lecture times: 
- lecture: Thursday, 16:00-17:30 in 100/U1/HS VI
- exercise classes: Monday, 16:00-17:30 in 103/EG/0.211

** Textbooks
The course is not based on a single textbook. The majority of topics is covered in cite:zweifel2009health. cite:morrisey2008health covers also many of the discussed topics but has an (almost entirely) empirical approach. Detailed references are given in the schedule below.

* Detailed schedule
This is a plan and as every good plan it may be adjusted if necessary.
** Introduction
- economic approach (trade-offs, choice-preferences-utility maximization, uncertainty, models)
- tools (optimization, regression analysis and endogeneity)
** Imperfect information between patient and insurer
*** demand for insurance
- full coverage (ch. 3 cite:morrisey2008health)
- coverage choice (ch. 5.3.1 and 5.3.2 cite:zweifel2009health) 
- supplementary reading: ch. 6.3 cite:zweifel2009health
*** adverse selection
- fixed coverage 
- menus and distortions 
- premium risk, community rating and risk adjustment 
- main reading: p. 115-123 cite:einav2011selection, ch. 5.3.3-5.3.4 cite:zweifel2009health
- supplementary reading:  cite:rothschild1976equilibrium, cite:stiglitz1977monopoly, cite:lagerlof2018monopoly, ch. 7 cite:zweifel2009health, cite:behrend2007risk, cite:PMM2000755
*** advantageous selection and beyond
- advantageous selection: cite:hemenway1990propitious, cite:fang2008sources, cite:finkelstein2006multiple
- positive correlation test and its pitfalls: cite:boone2017networks

*** moral hazard
- RAND and Oregon health insurance experiments
- bunching estimators at the donut hole
- simple model of moral hazard
- reading: cite:einav2018moral, ch. 6.4.2 cite:zweifel2009health
- supplementary reading: cite:dave2009health, cite:aron2013rand
** Imperfect information between doctor and patient
*** supply induced demand
- reading: ch. 8 cite:zweifel2009health 
- supplementary reading: cite:fuchs1978supply,gruber1996physician, cite:krasnik1990changing
# (also slides Wambach)
*** models of doctor patient interaction
# (slides Wambach)
- strategic communication and the hippocratic oath cite:schottmueller2013cifd
*** credence good models
cite:wolinsky1993competition 
# (slides Wambach)
** Imperfect information between doctor and insurer (and patient)
*** credence good models with insurance
# (slides Wambach)
*** selective contracting and managed care
- consumer steering and competition: cite:boone2017networks

# *** doctor renumeration under a global budget 
# cite:benstetter2006treadmill
*** health care payment systems
cite:ma1997optimal 



bibliographystyle:chicago
bibliography:/home/christoph/stuff/bibliography/references.bib

