#+TITLE: Imperfect Information in Health Care Markets
#+AUTHOR: Christoph Schottmüller
#+Options: toc:nil H:2
#+Latex_Header: \usepackage{natbib}

* News
# - The optional post exam review takes place on April 17 between 10:00 and 11:30. Further information can be found [[https://www.wiso.uni-koeln.de/de/studium/studienorganisation/klausureinsichtnahmen/gesundheitsoekonomie/][here]].
# - The exam results have been forwarded to the examination office. The post-exam review will take place after the term break and a specific date will be announced later. 
# - Information on the exam: 
#  - The exam is "/closed book/" but you are allowed to bring a pocket calculator that is (i) not programmable and (ii) not graphical. 
#  - The second exam date is March 22, 8:45-9:45 in Aula I.
#  - The exam will take place on February 7, 15:30-16:30 in HSI.
#  - Students asked me to indicate some exercise questions that could be exam questions with a rough idea of how many points these exercises would give. I give some examples in the following, however, the point estimates are rough and may differ from the way points are awarded int he exam. 
 #   - Insurance demand: exercise 5 and 6 (10 points each)
 #   - adverse selection: exercise 1a (5 points), 1d (5 points), 1e+1f (together 10 points), 1h (10 points)
 #   - moral hazard: exercise 4 (10 points) 
- Note that there will be an exercise session on October 7 even though this is before the first lecture covering [[https://github.com/schottmueller/infohealthecon/files/3685313/Exercise.Sheet.1.pdf][these]] questions. This exercise session is dedicated to repeating some mathematical concepts used in this course (distributions, expected value etc.). 

* Prerequisites and background
Several students asked for references for the prerequisites in terms of mathematics, statistics and microeconomics. For all of these areas there are literally hundreds of books titled "(Intermediate/Introductory) Microeconomics" or "Mathematics/Statistics for Business/Economics" and all of them cover more or less the same material. For concreteness, I name "Intermediate Microeconomis" ("Grundzüge der Mikroökonomik") by Hal Varian where chapters 1-6 are assumed to be known and chapter 12 is what we covered in the second lecture. Chapters 14-16 might be interesting background reading as well. For mathematics, "Essential Mathematics for Economic Analysis" by Sysdsæter, Hammond, Strøm and Carvajal may be useful. German speaking students may also be interested in Peter Dörsam's book "Mathematik anschaulich dargestellt für Studierenede der Wirtschaftswissenschaften". I am not familiar with statistics books but everything targeted at first semester business/economics students should be fine. Essentially, you have to know what a distribution is, how to compute an expected value and a variance, what a hypothesis test is and how an OLS regression works. Throughout the course we assume that your high school math knowledge is working and we have no time to repeat this material, e.g. make sure you can solve linear and quadratic equations, take derivatives and know their interpretation and integrate simple functions before week 1 of the semester.

If you want to take a less broad approach in catching up, the internet offers a variety of materials and formats (lecture notes, video tutorials on major online video platforms, interactive websites) that can be found with the usual search engines. For example, Wikipedia provides short definitions and explanations on all above metnioned topics (and often links to more in depth material). 

* Course material

Please note that I do not use ILIAS because (i) I did not agree with certain usage conditions concerning tracking and data utilization and (ii) I believe that the material I create should be publically available as it is essentially funded by public money. The material below is likely to get updated over the course of the term.

The course plan as [[https://github.com/schottmueller/infohealthecon/files/2437665/plan.pdf][pdf]] on which you can also find a list of references.

Lecture slides and exercises are posted/updated here over the course of the term. You can find the source code creating the slides as Emacs org-mode files (".org") [[https://github.com/schottmueller/infohealthecon/tree/master/slides][here]].

The exercises are available in [[https://github.com/schottmueller/infohealthecon/files/2803399/ex.pdf][pdf]] and as [[https://github.com/schottmueller/infohealthecon/blob/master/exercises/ex.org][.org]] file. Exercises for the first week are available [[https://github.com/schottmueller/infohealthecon/files/3685313/Exercise.Sheet.1.pdf][here]]. [[https://github.com/schottmueller/infohealthecon/blob/master/exercises/exercisePlots.ipynb][Plots]] shown in the exercise session. Here are the data sets for the case study on deductibles in the Netherlands for [[https://www.dropbox.com/s/05rnlf3rsbggy9r/data2011.csv?dl=0][2011]] and [[https://www.dropbox.com/s/2uupso7j89vllof/data2014.csv?dl=0][2014]]. 
# I posted some example analysis for the case study [[https://github.com/schottmueller/infohealthecon/blob/master/data/eigenRisico.org][here]].

- intro [[https://github.com/schottmueller/infohealthecon/files/3656685/intro.pdf][slides]]
- demand for insurance [[https://github.com/schottmueller/infohealthecon/files/3656693/insuranceDemand.pdf][slides]]
- (adverse) selection [[https://github.com/schottmueller/infohealthecon/files/2724228/adverseSelection.pdf][slides]], numerical [[https://github.com/schottmueller/infohealthecon/blob/master/julia/HealthInsuranceNoSingleCrossing.ipynb][example]] no single crossing
- moral hazard [[https://github.com/schottmueller/infohealthecon/files/2769026/moralHazard.pdf][slides]]
- physician-patient [[https://github.com/schottmueller/infohealthecon/files/2791900/doctorPatient.pdf][slides]]

** Julia notebooks
There are some julia/jupyter notebooks that can compute the resuls to some of the exercises or create the plots I use. The idea is the following: If you want to practice more, you can simply change the income or the utility function and redo the exercise with these new primitives. The code allows you to check whether your calculation were correct. On how to set up julia -- which is free and open source software -- see [[https://lectures.quantecon.org/jl/getting_started_julia/index.html][here]]. 


* Course setup 
In this course, we will analyze the consequences of information problems in health care markets and look for possible solutions to those problems on a theoretical basis. The theoretical analysis is at times supplemented with empirical evidence.

Students learn economic methods to analyze health care markets theoretically and also gain some insight in how to design empirical tests of the predictions of the theoretical models. 

The course consists of a lecture and an exercise session. Models, their solutions and implications as well as empirical evidence are presented in the lecture. In the exercise classes, solution to exercises are discussed. Students are expected to work on the exercises beforehand. Exercises consist mainly of calculation exercises using (variations of) models introduced in class but also discussion questions on specific applications. 

The exam will -- in style -- be similar to the questions of the exercise classes.

** Lecture times: 
- lecture: Wednesday, 12:00-13:30 in 100/U1/HS VI
- exercise classes: Monday, 14:00-15:30 in 103/EG/0.211

** Textbooks
The course is not based on a single textbook. The majority of topics is covered in cite:zweifel2009health. cite:morrisey2008health covers also many of the discussed topics but has an (almost entirely) empirical approach. Detailed references are given in the schedule below.

* Detailed schedule
This is a plan and as every good plan it may be adjusted if necessary.
** Introduction
- economic approach (trade-offs, choice-preferences-utility maximization, uncertainty, models)
- tools (optimization, regression analysis and endogeneity)
** Imperfect information between patient and insurer
*** demand for insurance
- full coverage (ch. 3 cite:morrisey2008health)
- coverage choice (ch. 5.3.1 and 5.3.2 cite:zweifel2009health) 
- supplementary reading: ch. 6.3 cite:zweifel2009health
*** adverse selection
- fixed coverage 
- menus and distortions 
- premium risk, community rating and risk adjustment 
- main reading: p. 115-123 cite:einav2011selection, ch. 5.3.3-5.3.4 cite:zweifel2009health
- supplementary reading:  cite:rothschild1976equilibrium, cite:stiglitz1977monopoly, cite:lagerlof2018monopoly, ch. 7 cite:zweifel2009health, cite:behrend2007risk, cite:PMM2000755
*** advantageous selection and beyond
- advantageous selection: cite:hemenway1990propitious, cite:fang2008sources, cite:finkelstein2006multiple
- positive correlation test and its pitfalls: cite:boone2017networks

*** moral hazard
- RAND and Oregon health insurance experiments
- bunching estimators at the donut hole
- simple model of moral hazard
- reading: cite:einav2018moral, ch. 6.4.2 cite:zweifel2009health
- supplementary reading: cite:dave2009health, cite:aron2013rand
** Imperfect information between doctor and patient
*** supply induced demand
- reading: ch. 8 cite:zweifel2009health 
- supplementary reading: cite:fuchs1978supply,gruber1996physician, cite:krasnik1990changing
# (also slides Wambach)
*** models of doctor patient interaction
# (slides Wambach)
- strategic communication and the hippocratic oath cite:schottmueller2013cifd
# *** credence good models
# cite:wolinsky1993competition 
# (slides Wambach)
** Imperfect information between doctor and insurer (and patient)
# *** credence good models with insurance
# (slides Wambach)
*** selective contracting and managed care
- consumer steering and competition: cite:boone2017networks

# *** doctor renumeration under a global budget 
# cite:benstetter2006treadmill
*** health care payment systems
cite:ma1997optimal 



bibliographystyle:chicago
bibliography:/home/christoph/stuff/bibliography/references.bib

