#+TITLE: Imperfect Information in Health Care Markets
#+AUTHOR: Christoph Schottmüller
#+Options: toc:nil H:2
#+Latex_Header: \usepackage{natbib}

* News
- Unfortunately, the board of examiners has decided that no exam inspections are allowed to take place for the time being. We hope that this slightly odd situation will change soon and we will then schedule a date for the exam inspection as soon as possible (here and on the exam office's website).
# - some points on the exam:
#  - In calculation exercises answering "2+√2" is fine. There is no need to calculate that this equals 3.4142....
#  - In essay type questions, the default should be to answer in complete sentences (no single word bullet points or similar).
#  - Explain your answers. In calculation exrcises the explanations can be brief and complete sentences are not required. 
# - On Jan. 15, we will discuss the empirical case study in the lecture (see the "exercises"). I will use LibreOffice Calc in class and provide a solution in Julia online. Please try to solve it yourself beforehand.
# - The optional post exam review takes place on April 17 between 10:00 and 11:30. Further information can be found [[https://www.wiso.uni-koeln.de/de/studium/studienorganisation/klausureinsichtnahmen/gesundheitsoekonomie/][here]].
# - The exam results have been forwarded to the examination office. The post-exam review will take place after the term break and a specific date will be announced later. 
# - Information on the exam: 
#  - The exam is "/closed book/" but you are allowed to bring a pocket calculator that is (i) not programmable and (ii) not graphical. 
#  - The second exam date is March 22, 8:45-9:45 in Aula I.
#  - The exam will take place on February 3, 16:15-17:15 in HS B.
#  - Students asked me to indicate some exercise questions that could be exam questions with a rough idea of how many points these exercises would give. I give some examples in the following, however, the point estimates are rough and may differ from the way points are awarded int he exam. 
 #   - Insurance demand: exercise 5 and 6 (10 points each)
 #   - adverse selection: exercise 1a (5 points), 1d (5 points), 1e+1f (together 10 points), 1h (10 points)
 #   - moral hazard: exercise 4 (10 points) 
# - Note that there will be an exercise session on October 7 even though this is before the first lecture covering [[https://github.com/schottmueller/infohealthecon/files/3685313/Exercise.Sheet.1.pdf][these]] questions. This exercise session is dedicated to repeating some mathematical concepts used in this course (distributions, expected value etc.). 

* Prerequisites and background
Several students asked for references for the prerequisites in terms of mathematics, statistics and microeconomics. For all of these areas there are literally hundreds of books titled "(Intermediate/Introductory) Microeconomics" or "Mathematics/Statistics for Business/Economics" and all of them cover more or less the same material. For concreteness, I name "Intermediate Microeconomis" ("Grundzüge der Mikroökonomik") by Hal Varian where chapters 1-6 are assumed to be known and chapter 12 is what we covered in the second lecture. Chapters 14-16 might be interesting background reading as well. For mathematics, "Essential Mathematics for Economic Analysis" by Sysdsæter, Hammond, Strøm and Carvajal may be useful. German speaking students may also be interested in Peter Dörsam's book "Mathematik anschaulich dargestellt für Studierenede der Wirtschaftswissenschaften". I am not familiar with statistics books but everything targeted at first semester business/economics students should be fine. Essentially, you have to know what a distribution is, how to compute an expected value and a variance, what a hypothesis test is and how an OLS regression works. While it skips some of the basic statistics the first 2 chapters in "Mastering Metrics: The path from cause to effect" by Angrist and Pischke might be used as an application oriented introduction to empirical work. Throughout the course we assume that your high school math knowledge is working and we have no time to repeat this material, e.g. make sure you can solve linear and quadratic equations, take derivatives and know their interpretation and integrate simple functions before week 1 of the semester.

If you want to take a less broad approach in catching up, the internet offers a variety of materials and formats (lecture notes, video tutorials on major online video platforms, interactive websites) that can be found with the usual search engines. For example, Wikipedia provides short definitions and explanations on all above mentioned topics (and often links to more in depth material). 

* Course material

Please note that I do not use ILIAS because (i) I did not agree with certain usage conditions concerning tracking and data utilization and (ii) I believe that the material I create should be publically available as it is essentially funded by public money. The material below is likely to get updated over the course of the term.

Lecture slides and exercises are posted/updated here over the course of the term. You can find the source code creating the slides as Emacs org-mode files (".org") [[https://github.com/schottmueller/infohealthecon/tree/master/slides][here]].

- The *course plan* as [[https://github.com/schottmueller/infohealthecon/files/5168062/plan.pdf][pdf]] on which you can also find a list of *references*.

- The *exercises* are available as [[https://github.com/schottmueller/infohealthecon/files/5162934/exercises.pdf][pdf]] and as [[https://github.com/schottmueller/infohealthecon/blob/master/exercises/exercises.org][org]] file. Exercises for the first week are available [[https://github.com/schottmueller/infohealthecon/files/3685313/Exercise.Sheet.1.pdf][here]]. [[https://github.com/schottmueller/infohealthecon/blob/master/exercises/exercisePlots.ipynb][Plots]] shown in the exercise session (use this [[https://nbviewer.jupyter.org/github/schottmueller/infohealthecon/blob/master/exercises/exercisePlots.ipynb][link]] if github cannot render the file). 

- *Slides*
  - intro [[https://github.com/schottmueller/infohealthecon/files/5162914/01intro.pdf][slides]]
  - demand for insurance [[https://github.com/schottmueller/infohealthecon/files/5162915/02insuranceDemand.pdf][slides]]
  - (adverse) selection [[https://github.com/schottmueller/infohealthecon/files/5162916/0307adverseSelection.pdf][slides]],   numerical [[https://github.com/schottmueller/infohealthecon/blob/master/julia/HealthInsuranceNoSingleCrossing.ipynb][example]] no single crossing
  - moral hazard [[https://github.com/schottmueller/infohealthecon/files/5162917/0810moralHazard.pdf][slides]]
  - physician-patient [[https://github.com/schottmueller/infohealthecon/files/5162918/1114doctorPatient.pdf][slides]]

- *Data sets* for cases studies:
  - [[https://web.tresorit.com/l/LgFab#pgfSdjSm0wf4oAtRpkybYQ][Data]] on selection in long term care insurance. (password announced in lecture)
  - Data on deductibles in the Netherlands for [[https://www.dropbox.com/s/05rnlf3rsbggy9r/data2011.csv?dl=0][2011]] and [[https://www.dropbox.com/s/2uupso7j89vllof/data2014.csv?dl=0][2014]]. 
# pw is "infohealth"
# I posted some example analysis for the case study [[https://github.com/schottmueller/infohealthecon/blob/master/data/eigenRisico.org][here]].

- An [[https://github.com/schottmueller/infohealthecon/files/3968257/exam2019-2questions.pdf][old exam]] is available.

** Julia notebooks
There are some julia/jupyter notebooks that can compute the resuls to some of the exercises or create the plots I use. The idea is the following: If you want to practice more, you can simply change the income or the utility function and redo the exercise with these new primitives. The code allows you to check whether your calculation were correct. On how to set up julia -- which is free and open source software -- see [[https://lectures.quantecon.org/jl/getting_started_julia/index.html][here]]. If you want to learn julia from scratch, you can check the free online book [[https://benlauwens.github.io/ThinkJulia.jl/latest/book.html][ThinkJulia]] or use the online courses on [[https://www.coursera.org/learn/julia-programming][Coursera]] or [[https://juliaacademy.com/][JuliaAcademy]].


* Course setup 
In this course, we will analyze the consequences of information problems in health care markets and look for possible solutions to those problems on a theoretical basis. The theoretical analysis is at times supplemented with empirical evidence.

Students learn economic methods to analyze health care markets theoretically and also gain some insight in how to design empirical tests of the predictions of the theoretical models. 

The course consists of a lecture and an exercise session. Models, their solutions and implications as well as empirical evidence are presented in the lecture. In the exercise classes, solution to exercises are discussed. Students are expected to work on the exercises beforehand. Exercises consist mainly of calculation exercises using (variations of) models introduced in class but also discussion questions on specific applications. 

The exam will -- in style -- be similar to the questions of the exercise classes.

** Lecture times: 
- lecture: Wednesday, 12:00-13:30 in 100/U1/HS VI
- exercise classes: Monday, 12:00-13:30 online in week 1, otherwise  14:00-15:30 in 100/HSXII

** Textbooks
The course is not based on a single textbook. The majority of topics is covered in cite:zweifel2009health. cite:morrisey2008health covers also many of the discussed topics but has an (almost entirely) empirical approach. Detailed references are given in the schedule below.

* Detailed schedule
This is a plan and as every good plan it may be adjusted if necessary.
** Intro (2 lectures)
*** Choice, preferences, utilities, welfare, models
- choice, preferences, utility
- choice under uncertainty and expected utility
- welfare
- models
- reading: 
*** Insurance demand
- certainty equivalent and risk premium
- drivers of insurance demand
- (coverage choice and state dependent utility)
- reading: ch. 3 cite:morrisey2008health
- supplementary reading: (Springer book Bachelor)

** Selection (5)
*** Selection with fixed coverage
- model
- welfare consequences
- gender specific premia
- some evidence for selection
- reading: p. 115-123 cite:einav2011selection, ch. 5.3.1 and 5.3.2 cite:zweifel2009health
*** Screening with coverage: Rothschild-Stiglitz
- shape of indifference curves
- equilibrium 
- comparative statics
- derivation of eq in screencast
# - reading:  ch. 5.3.3-5.3.4 cite:zweifel2009health ?? oder ch. 7?
- supplementary reading: cite:rothschild1976equilibrium
*** Genetic Tests
- two kinds of risks
- in RS model
- supplementary reading: cite:doh96
*** Premium risk, community rating and risk adjustment
- premium risk model
- segway into risk adjustment
- discussion: how could German health insurers attract a profitable clientele?
- supplementary reading: cite:behrend2007risk, cite:PMM2000755
*** Advantageous selection
- empirical observations (provide Finkelstein/McGarry data and compute results live in lecture)
- fixed coverage model
- (treatment choice and utilization...maybe as bonus screencast?)
- reading: cite:finkelstein2006multiple
- supplementary reading: cite:hemenway1990propitious, cite:fang2008sources
** Moral hazard (3)
*** The question of moral hazard and empirical evidence
- slope of demand
- RAND and arc elasticity of demand
- Oregon
- welfare
- ex ante moral hazard
- reading: sections 1,2 and 3.1 in cite:einav2018moral
*** Treatment choice and the donut hole 
- simple model of treatment choice
- donut hole
- out of sample predictions
- utilization management and gatekeeping
- reading: section 3.2-end cite:einav2018moral
*** Case study: moral hazard in NL
- diff-in-diff estimate for arc elasticity of demand

** Doctor-patient interaction (4)
*** Supplier induced demand: theory
- density model
- some empirical evidence
- second wave of SID studies
- reading: ch. 8 cite:zweifel2009health
- supplementary reading: section 5 in cite:mcguire2000physician, cite:fuchs1978supply,gruber1996physician, cite:krasnik1990changing
*** Supplier induced demand: empirics
- How Danish physicians react to incentives
- Caesarean sections in German hospitals
*** Credence good model
- problems/assumptions and appropriate incentives
- discussion: DRG system like liability? implications?
- reading: cite:dulleck2006doctors
*** Cost saving incentives and communication



bibliographystyle:chicago
bibliography:/home/christoph/stuff/bibliography/references.bib

