#+Title: Exercises
#+AUTHOR:    Christoph Schottmüller
#+Date: 

#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:nil 
#+OPTIONS:   TeX:t LaTeX:t 

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+latex_header: \usepackage{amsmath}\usepackage[margin=2.5cm]{geometry}\usepackage{ae,aecompl}\usepackage{sgame}

* Introduction
1. Assume that the utility function $u_i$ represents $i$'s preferences over a set of alternatives $X=\{x_1,x_2,\dots,x_n\}$. Show that
  1. $i$'s preferences are transitive;
  2. the function $v_i$ defined by $v_i(x)=f(u_i(x))$ also represents $i$'s preferences if $f$ is a strictly increasing function.
  3. Assume now that there are only 2 alternatives, i.e. $X=\{x_1,x_2\}$. Assume that there are 2 people in the society and person 1 prefers $x_1$ over $x_2$ while person 2 prefers $x_2$ over $x_1$. Choose some utility functions $u_1$ and $u_2$ to represent their preferences. Assume that society chooses the alternative $x$ maximizing $u_1(x)+u_2(x)$. 
    - Which alternative does society choose with the utility functions you chose? 
    - Show that a transformation as in the previous subquestion can change society's choice. What is the problem and how does it come about? 

2. Assume that there are $m$ people in society and society has to choose an option from  $X=\{x_1,x_2,\dots,x_n\}$. The preferences of each member of society can be represented by a utility function $u_i$. Society choose the alternative $x\in X$ maximizing $\sum_{i=1}^m u_i(x)$. Show that the chosen alternative is Pareto efficient.

3. Assume $i$'s preferences over lotteries on the set of outcomes $\{healthy,\,ill,\,dead\}$ satisfy the assumptions of the von Neumann-Morgenstern expected utility theorem and can therefore be represented by three numbers $u^{healthy},\,u^{ill}$ and $u^{dead}$. Assume that  $u^{healthy}=1,\,u^{ill}=0.75$ and $u^{dead}=0$.
  1. Treatment 1 leads to the probability distribution over $(0.3,0.5,0.2)$ (over $\{healthy,\,ill,\,dead\}$) while treatment 2 leads to the probability distribution $(0.4,0.3,0.3)$. Which treatment does $i$ prefer?
  2. Show that $i$'s preferences over lotteries can also be represented by the three numbers $v^{healthy}=a*u^{healthy}+b$, $v^{ill}=a*u^{ill}+b$ and $v^{dead}=a*u^{dead}+b$ where $a>0$ and $b\in\Re$ are some real numbers.
  3. Show by means of an example that $i$'s preferences are not necessarily represented by $v^{healthy}=f(u^{healthy})$, $v^{ill}=f(u^{ill})$ and $v^{dead}=f(u^{dead})$ for some strictly increasing function $f$.
