#+Title: Exercises
#+AUTHOR:    Christoph Schottmüller
#+Date: 

#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:nil 
#+OPTIONS:   TeX:t LaTeX:t 

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+latex_header: \usepackage{amsmath}\usepackage[margin=2.5cm]{geometry}\usepackage{ae,aecompl}\usepackage{sgame}

* Introduction
1. Assume that the utility function $u_i$ represents $i$'s preferences over a set of alternatives $X=\{x_1,x_2,\dots,x_n\}$. Show that
  1. $i$'s preferences are transitive;
  2. the function $v_i$ defined by $v_i(x)=f(u_i(x))$ also represents $i$'s preferences if $f$ is a strictly increasing function.
  3. Assume now that there are only 2 alternatives, i.e. $X=\{x_1,x_2\}$. Assume that there are 2 people in the society and person 1 prefers $x_1$ over $x_2$ while person 2 prefers $x_2$ over $x_1$. Choose some utility functions $u_1$ and $u_2$ to represent their preferences. Assume that society chooses the alternative $x$ maximizing $u_1(x)+u_2(x)$. 
    - Which alternative does society choose with the utility functions you chose? 
    - Show that a transformation as in the previous subquestion can change society's choice. What is the problem and how does it come about? 

2. Assume that there are $m$ people in society and society has to choose an option from  $X=\{x_1,x_2,\dots,x_n\}$. The preferences of each member of society can be represented by a utility function $u_i$. Society choose the alternative $x\in X$ maximizing $\sum_{i=1}^m u_i(x)$. Show that the chosen alternative is Pareto efficient.

3. Assume $i$'s preferences over lotteries on the set of outcomes $\{healthy,\,ill,\,dead\}$ satisfy the assumptions of the von Neumann-Morgenstern expected utility theorem and can therefore be represented by three numbers $u^{healthy},\,u^{ill}$ and $u^{dead}$. Assume that  $u^{healthy}=1,\,u^{ill}=0.75$ and $u^{dead}=0$.
  1. Treatment 1 leads to the probability distribution over $(0.3,0.5,0.2)$ (over $\{healthy,\,ill,\,dead\}$) while treatment 2 leads to the probability distribution $(0.4,0.3,0.3)$. Which treatment does $i$ prefer?
  2. Show that $i$'s preferences over lotteries can also be represented by the three numbers $v^{healthy}=a*u^{healthy}+b$, $v^{ill}=a*u^{ill}+b$ and $v^{dead}=a*u^{dead}+b$ where $a>0$ and $b\in\Re$ are some real numbers.
  3. Show by means of an example that $i$'s preferences are not necessarily represented by $v^{healthy}=f(u^{healthy})$, $v^{ill}=f(u^{ill})$ and $v^{dead}=f(u^{dead})$ for some strictly increasing function $f$. Why does this not contradict our result from exercise 1 above?

* Insurance demand
In all exercises let the person be an expected utility maximizer, i.e. the person's choices satisfy the assumptions of the von Neumann-Morgenstern expected utility theorem.

1. Consider a person with utility of income $u(x)=\sqrt{x}$. Is this person risk averse? For the following lotteries, compute the expected income, the certainty equivalent and the risk premium.
  1. Probability $1/3$ for each $1600$, $2500$, and $3600$ Euros.
  2. Income is uniformly distributed between 1600 and 2500 Euros.

2. Consider a person with utility of income $u(x)=\sqrt{x}$. The person has an income of $2500$ Euros but loses $L$ Euros with probability $\alpha$. Determine the certainty equivalent and the risk premium as a function of $\alpha$ and $L$. Is the risk premium increasing or decreasing in $L$? Is  the risk premium increasing or decreasing in $\alpha$?

3. Consider the utility function $u(x)=-e^{-\eta x}$. The person has an income of $1$ and experiences a loss of $1$ with probability $\alpha$.  The coefficient of absolute risk aversion is defined as $-u''(x)/u'(x)$. Compute this coefficient. Let now $\alpha=0.5$ and check whether the certainty equivalent in- or decreases in $\eta$.

4. The Wall Street Journal reported in 2006 of "mini-medical insurance plans". These plans cover routine services, but little hospital coverage and usually have a cap on payouts (say of $ 10.000 ). The premium, however, is only $ 50 per month. Why might people buy a mini-medical plan? Why are such insurance plans not more popular (in a country where a substantial part of the population did/does not have health insurance)?  

5. Consider a person with utility of income $u(x)=\sqrt{x}$. The person has an income of $2500$ Euros but loses $1500$ Euros with probability $1/4$. Assume there is an insurance company that offers to insure an arbitrary coverage $C\in[0,1500]$ at premium $pC$. Determine the amount of coverage $C(p)$ that the person will buy. (If you find this too hard, let $p$ be 0.3.)

6. Consider the same person as in the previous exercise. Let $p=0.3$ and suppose the government guarantees a minimum income of 1500. Will the person still buy insurance? Discuss what features of the health care sector are similar to a minimum income guarantee in the model.



# E1: a) E[u]=50, E[x]=2566.6, CE=2500, RP=66.6; b) E[u]=45.185 E[x]=2050 CE=2041.7 RP = 8.3

# E2: \sqrt{CE} = \alpha \sqrt{2500-L}+(1-\alpha) \sqrt{2500}; CE= \alpha^2 (2500-L)+(1-\alpha)^2 2500+\alpha (1-\alpha) 100\sqrt{2500-L} = (5000-L) \alpha^2-5000\alpha+2500+(\alpha -\alpha^2)100 \sqrt{2500-L};  RP=2500-\alpha L -CE=(\alpha -\alpha^2)(5000-L-100 \sqrt{2500-L})

# E3: discuss why $u''$ is a bad measure of risk aversion (problem of multiplying u with a positive number);  $-u''(x)/u'(x)=\eta$ "constant absolute risk aversion" (CARA) -> higher eta means more risk aversion; usually coefficient depends on x but not with CARA preferences; -e^{-\eta CE}=-\alpha-(1-\alpha)e^{-\eta} and therefore CE = -log(\alpha+(1-\alpha)e^{-\eta})/\eta; plug in \alpha=0.5 and draw CE(\eta) numerically

# E4: no covering of large loss is against our theory; more of a smoothing out of expected costs than a real insurance; maybe mandate to treat in emergency rooms allows poor people to default on large claims (or get those waved) while claims up to 10.000 the provider may be able to collect; in any case catastrophe plans that cover only large losses are much more common

# E5: E[u]=\sqrt{1000+(1-p)C}/4+\sqrt{2500-pC}*3/4; foc: (1-p)/\sqrt{1000+(1-p)C}-3p/\sqrt{2500-pC}=0; yields C=(-6500p^2-5000p+2500)/(p(1-p)(1+8p)); for p=0.3 this is 1416.4; note: for p=1/4, C=1500; for p>1/4 C<1500; for p>(-5+\sqrt{90})/13=0.345 the calculated C becomes negative, i.e. the person will not buy insurance if the premium rate is too high

# E6: E[u]^{insurance}=45.32, E[u]^{no ins}=\sqrt{1000}/4+\sqrt{2500}*3/4=45.406; hence person will not buy insurance;  obligation to treat, i.e. doctors/emergeny rooms/hospitals cannot turn back people even if they cannot pay (or pay only partially); literal social assistance

* Adverse selection 
1. We now have a continuum of people of length $1/2$. More precisely, we have a person $i$ for each $i\in[0,1/2]$. All people have the same utility function $u(x)=\sqrt{x}$ and the same income of 2500. However, they differ in terms of risk: Person $i$ loses 1600 with probability $i$. We consider an insurance policy with full coverage, i.e. a policy that pays out 1600 in case of a loss. Every person knows his own risk but insurance companies cannot distinguish people (and will therefore have to offer the same premium to everybody). 
  1. Determine the willingness to pay for the insurance of person $i$. 
  2. For every possible insurance premium, how many people will buy insurance? Use your results to draw the demand for insurance. 
  3. Determine the marginal cost of person $i$.
  4. Determine the average cost of insuring all people $i\geq j$, i.e. everyone in $[j,1/2]$.
  5. If many risk neutral insurance companies with no administrative costs are active on this market, what is the market equilibrium?
  6. Is the market equilibrium efficient? If not, determine the size of the inefficiency. What would be welfare in "first best", i.e. in a situation in which everyone with a willingness to pay above marginal cost gets insurance? Determine the relative inefficiency due to adverse selection.
  7. Consider an insurance subsidy to insurers, i.e. each insurer receives for each sold insurance a subsidy payment $s$. How high does $s$ have to be to ensure efficiency? 
  8. Consider an insurance mandate (without subsidies), i.e. everyone is forced to buy an insurance contract. What is the equilibrium insurance premium? Who will benefit from the mandate? Who will lose out with the mandate?
  9. Suppose insurers can now distinguish two groups: The people $i\geq 0.3$ and the people $i< 0.3$. Assume that insurers are allowed to offer different contracts to these two groups. Consequently, there are now two separate markets. What is the equilibrium on the "high risk market"? What is the equilibrium on the "low risk" market? Is the new situation more or less efficient than the one considered in the previous subquestions? Who benefits from groups discrimination and who does not?
  10. With the previous subquestion in mind, what happens if insurers can identify people better? (For example, distinguish more and more subgroups as in the previous subquestion.) What are the consequences for welfare? Who benefits and who loses?

2. You work for a profit maximizing health insurer which recently understood the problem of adverse selection. Your boss asks you what to do to increase/maintain profits in light of the adverse selection problem. What do you answer?

3. In this exercise we show that in the Rothschild-Stiglitz model only one contract per type can be sold in equilibrium. We do this by contradiction. Suppose this was not true, i.e. suppose there were two contracts $(p_1,q_1)$ and $(p_2,q_2)$ that are bought by consumers with high risk. 
  1. Draw in a coverage, premium diagram such two contracts and the indifference curve of the high risk consumers.
  2. Draw the isoprofit lines of the insurers through these contracts.
  3. Find a deviation contract that yields strictly positive profit (and is bought by some players if offered).
  4. Now suppose there were two contracts $(p_1,q_1)$ and $(p_2,q_2)$ that are bought by consumers with /low/ risk. Do the same as above but be careful when arguing that the deviation contract is strictly profitable.

4. In the Rothschild-Stiglitz model, assume that all consumers have the utility function $u(x)=-0.5x^2+10x$, that $W=9$, $L=5$, $\alpha_h=1/2$ and $\alpha_l=1/4$.
  1. Derive the isoprofit curve of an insurance company insuring a consumer with risk $\alpha$, i.e.   if coverage is $q$ what does the premium have to be to achieve expected profits of $\bar \pi$?
  2. Derive the consumer's indifference curve, i.e. if coverage is $q$ what does the premium have to be to achieve an expected utility of $\bar U$?
  3. Verify that the slope of the indifference curve of a consumer with higher risk is higher. Verify that the slope of the indifference curve is higher than the slope of the isoprofit curve for $q<1$ and equal for $q=1$.
  4. If risk types were observable what would be the equilibrium contracts for the two risk types?
  5. What is the Rothschild-Stiglitz equilibrium (i.e. the equilibrium when risk types are not observed by the insurance companies)? For which shares of high risk types is there a full coverage pooling contract breaking this equilibrium?  

5. Suppose the government mandates that coverage levels have to be at least $\bar q$. How does this affect the Rothschild-Stiglitz equilibrium? Who benefits/loses from this intervention?

6. Suppose that a low risk type is indifferent between his contract in the Rothschild-Stiglitz equilibrium candidate and a full coverage contract at premium $(\gamma\alpha_h+(1-\gamma)\alpha_l)*L$. What interpretation does the premium $(\gamma\alpha_h+(1-\gamma)\alpha_l)*L$ have? Demonstrate that in this case the Rothschild-Stiglitz equilibrium does not exist.

7. In the Netherlands, health insurance contracts can only be changed at the end of the calendar year. Discuss why such a regulation may or may not be a good idea. Do you know of other similar provisions or regulations?

8. Consider an insurance market where everyone has the \emph{same risk } of falling ill but people differ in their degree of risk aversion. More concretely, assume that everyone has the utility function $u(x)=-e^{-\eta x}$ and that a share $\gamma$ of the population has a high degree of risk aversion, $\eta= \eta_h$, while a share $1-\gamma$ of the population has a low degree of risk aversion, $\eta=\eta_l<\eta_h$. Everything else is as in the Rothschild-Stiglitz model. In particular, we assume a perfectly competitive market, i.e. many insurance companies competing in menus of coverage, premium pairs. What will be the equilibrium on this market?

# E1.1: \sqrt{2500-WTP}=i\sqrt{900}+(1-i)\sqrt{2500}, WTP=2000i-400i^2
# E1.2: 0 for p>=900; critical i: p=2000i-400i^2; i(p)=2.5-\sqrt{6.25-p/400}; D(p)= 1/2-i(p)= \sqrt{6.25-p/400}-2
# E1.3: MC(i)=i*1600; 
# E1.4: AC(j)=(1/2+j)*800
# E1.5: critical i: AC(i)=WTP(i); i = 1.5-\sqrt{5}/2\approx 0.38; hence i in [0.38,0.5] buy insurance
# E1.6: \int_{0.38}^{1/2}WTP(i)-MC(i)\,di=400[i^2/2-i^3/3]_0.33^{0.5}=11.584; welfare:  \int_{0}^{0.5}WTP(i)-MC(i)\,di=400[i^2/2-i^3/3]_0^{0.5}=33.333; proportional loss: 11.584/33.33=0.347
# E1.7: AC^s(i)=AC(i)-s; equilibrium AC^s(i)=WTP(i); 800(.5+i)-s=2000i-400i^2; cover everyone means i=0 and therefore s=400.
# E1.8: p^*=AC(0) hence p=400, benefit if WTP(i)>=400, loose else; benefit if i>0.209
# E1.9: for i>0.3 same as original question; for i<0.3 AC(i)=(0.3+i)*800 and AC(i^*)=p*=WTP(i^*) gives i^*=0.225 and therefore p^*=420; people in (0.225,03.) benefit everyone else's utility is unchanged

# E1.10: Problem of adverse selection disappears as for a small enough subgroup the AC will be below WTP for all people in the subgroup, i.e. everyone will buy insurance (almost everyone to be precise: WTP(0)=0 so $i=0$ and people will not buy insurance if bunched together with others but that is a special case). WElfare will therefore increase. However, note that people in the top categories might experience higher premiums: If the highest subgroup is [a,0.5] and a>0.38, then their premium increases and they do not benefit.  i<0.38 will benefit

# E2: problem is that one attracts high cost customers; to avoid this, tailor your insurance plan toward healthy people (bonus programs for fitness courses; pay back part of the insurance premium when care was not used in a given year) and make it unattractive for chronically ill and unfit (signing of contract requires you to go to an office in the 3rd floor without an elevator or only online to get rid of the expensive elderly; have offices in neighborhoods with where people with high socioeconomic status live as they tend to be healthier; do not cover certain brands of medication for chronic diseases to which people may be already attached etc.)

# E3: By the no pooling result, both contracts are bought by h consumers only. As both isoprofit lines have to yield non-negative profits, there are contracts with $q\in(q_1,q_2)$ and a premium just above the indifference curve that are preferred by h to the two offered contracts and are strictly profitable if bought by h. Note that attracting l types to the deviation contract can only increase profits. 
# E3.4: Same as before but now one has to argue that the deviation contract does not attract h consumers. Note that this is true if the deviation contract is sufficiently close to the indifference curve of the low risk consumer as in this case h prefers the original contract with higher coverage to the deviation contract.  

# E4:1: pi=p-alpha qL; p=pi+alpha q L
# E4.2: for alpha = 1/2 only: U =1/2[-1/2 (9-p-(1-q)5)^2+10(9-p-(1-q)5]+1/2[-1/2(9-p)^2+10(9-p)] which yields 4U = 163-2p^2+60q-25q^2-14 p+10pq or p=(5q-7)/2 + \sqrt{375-25q^2+50q-8U}/2; for alpha = 1/4: p(q)=(5q-9)/4+\sqrt{1525-75q^2+150q-32 U}/4
# E4.3: direct differentiation in 4.2 yields p'(q)=5/2+50(1-q)/[4\sqrt{}] for alpha=1/2 and p'(q)=5/4+150(1-q)/[8\sqrt{}] which gives the result for q close to 1; however not very useful as one does not compare slope at same contract (unless "right" utility levels are chosen); better to use implicit function theorem which as in lecture yields p'(q|\mathbb{E}[u]=\bar u)= L\frac{u'(W-p-(1-q)L)}{u'(W-p-(1-q)L)+\frac{1-\alpha}{\alpha}u'(W-p)} which looks at slope through a given contract and clearly higher alpha leads to higher slope. For isoprofit comparison p'(q)>=alpha L with equality only for q=1
# E4.4: zero profits and full coverage i.e. q=1 and p=alpha L
# E4.5: h get full cov at zero profit, i.e. p_h=5/2 and q_h=1, leading to expected utility u(9-5/2)=43.875. zero profits for l imply p_l=q_l*5/4; h is indifferent between bot contracts, hence 43.875 = .5*u(9-p_l-5+5q)+.5 u(9-p_l), or q_l=0.3355.. p_l=0.4193...; this is broken by a full coverage pooling contract if gamma<0.33651...

# E5: 
# if \bar q below q_l^*, no effect
# if \bar q > q_l^* and RS eq existed and \bar q not too big, then new eq with same contract for h and (p,\bar q) where p is on h's indiff curve; note that this is Pareto improvement as l is better off (his indiff is hlatter than h's) and positive profits from l type
# if \bar q too high, then no RS eq exists as potential eq (see above) is broken by pooling

# E6: point on zero profit pooling isoprofit for q=1; slope indiff l at q=1 is \alpha_l and therefore smaller than pooling isoprofit at 0 profit; hence deviation pooling contracts with q slightly below 1 exist

# E7: people switch from being low to being high risk and vice versa over time; if immediate change of plan is allowed people could buy the cheapest/no insurance and go to the plan with highest coverage the moment they fall ill; similar logic to German private plans that cover dental care only after 2 years

# E8: indifference curves of high risk aversion types are steeper and wtp for insurance is higher. There has to be full coverage in equilibrium as otherwisewe have a profitable full coverage deviation. Note that we cannot sustain a separating as increasing the low risk aversion coverage to 1 while keeping him indifferent is a profitable deviation (both types have the same expected costs). Hence, equilibrium is pooling on the average cost.

** Genetic tests
1. Assume that all people in our economy are similar and have the same Bernoulli utility function $u(x)=\sqrt{x}$. A person has wealth $W=9$ and falls ill with probability 1/2. When falling ill the person needs treatment costing $L=5$. 
  1. Determine the risk premium of a consumer for a full coverage contract. What contract will a profit maximizing insurance monopolist offer in this market?
  2. Suppose a genetic test becomes available: The test results can be either "high risk" (h) or "low risk" (l). Those that test have a 50% chance of getting either result. High risk people have probability 3/4 and low risk people have the probability 1/4 of falling ill. 
    - Calculate the risk premium of an /h/ type and the risk premium of an /l/ type (again using a full coverage contract).
    - Assume everyone gets tested and the insurance monopolist can make his contracts dependent of the test result. What contracts will he offer? How do profits and expected utility change compared to (a)?
    - Assume that the monopolist is prohibited from making his contract contingent upon the test results. How do expected utility and insurance profits change compared to (a)? (Note: you do not have to calculate the profit maximizing contracts to answer this question qualitatively.) 
  3. How does your answer to the previous subquestions change if we assume that the insurance market is perfectly competitive?

# E1a: no insurance: E[u]:.5*\sqrt{9}+.5*\sqrt{9-5}=2.5; 2.5=\sqrt{9-.5*5-RP} or RP=1/4; p^{mon}=.5*5+1/4=2.75
# E1b:  no insurance h: E[u]:.25*\sqrt{9}+.75*\sqrt{9-5}=9/4; 9/4=\sqrt{9-.75*5-RP} or RP=3/16; p^{mon}_h=.75*5+3/16=63/16, q_h^{mon}=1
#  no insurance l: E[u]:.75*\sqrt{9}+.25*\sqrt{9-5}=11/4; 11/4=\sqrt{9-.25*5-RP} or RP=3/16; p^{mon}_l=.25*5+3/16=23/16, q_l^{mon}=1
#  monopolist with observability: pi=3/16 which is lower than without test where it was 1/4; expected utility of types is E[u_h]=9/4 and E[u_l]=11/4 and therefore on average the same as without test
#  monopolist + adverse selection: Stiglitz model from lecture; E[u_l]=11/4 as l-contract on IR_l; E[u_h]>9/4 as h-contract below IR_h; profits<3/16 as (i) inefficient contract for l (q_l<1) --> lower isoprofit curve, (ii) lower premium for h
# E1c: 

** Premium risk
1. In Germany (private) health insurers are required to charge a constant premium over the life cycle. We use the premium risk model from the lecture: 2 periods, income $W$ in each period, everyone has low risk $\alpha_l$ of a loss $L$ in period 1, probability $1-\lambda$ of an increse of risk to $\alpha_h$ in period 2, perfect competition.
  1. Calculate the constant premium that yields zero expected profits to insurers under the assumption that no one switches insurers in period 2.
  2. Given the premium from the previous subquestion, what would happen if consumers could switch insurers in period 2?
  3. Compare the premium of the first subquestion with the premiums under "guaranteed renewal". What are the implications?
  4. Suppose now that in period 2 everyone's health deteriorates. More precisely, assume that the risk is $\alpha_m>\alpha_l$ with probability $\lambda$ and $\alpha_h>\alpha_m$ with probability $1-\lambda$. 
    - Calculate the constant premium that yields zero profits to insurers (without switching).
    - Compare it to the premiums with "guaranteed renewal". 

2. Discuss the advantages and disadvantages of using "last year health care expenditures of insured" as an explanatory variable in a risk adjustment scheme.

3. Suppose the population consists of two types /l/ and /h/ with the expenditure distribution for each type as in the table below. In this exercise we measure the incentive of an insurance to engage in risk selection by the difference in expected expenditures.
  1. Calculate the expected expenditures per risk type and the incentives to engage in risk selection.
  2. Consider a risk adjustment scheme that covers all expenditures above 20 (i.e. all expenditures above 20 are covered by some common fund). Calculate the expected expenditures per risk type that an insurer has to cover himself and the incentives to engage in risk selection. What is the idea behing such a risk adjustment scheme?
  3. Consider a risk adjustment scheme that covers all expenditures up to 8 (i.e. all expenditures up to 8 are covered by some common fund). Calculate the expected expenditures per risk type that an insurer has to cover himself and the incentives to engage in risk selection. 
  4. Consider expenditure distributions that satisfy the following conditions: $p_h^{30}>p_l^{30}$ and $p_h^{10}+p_h^{30}\geq p_l^{10}+p_l^{30}$ where $p_h^{30}$ is the probability that a high risk type has expenditures 30 and so on. 
    - Show that the  incentive to engage in risk selection are decreased by a risk adjustment scheme as in (b) for all such distributions.
    - Show that the  incentive to engage in risk selection are decreased by a risk adjustment scheme as in (c) for all such distributions.

| risk/expenditure |   0 |  10 |  30 |
|------------------+-----+-----+-----|
| /                |   < |     |     |
| /l/              | 40% | 10% | 50% |
| /h/              | 10% | 50% | 40% |


# 4. In the USA a prediction model similar to the German risk adjustment scheme is used to predict expenditures for  Medicare recipients (Medicare: subsidized care for elderly). That is an HMO (combined health insurer and care provider) is paid an amount $x$ for enrolling Medicare recipient Mister X where $x$ depends on the predicted care cost for Mister X. Over the years the scheme was changed several times:
#  - First, the prediction model was based on age, gender, location and wheter Mister X is eligible for welfare payments and the amount $x$ was 95% of the predicted expenditures.
# - In 1997 Medicare was reformed and the prediction model includes a hierarchical condition categories model (used in addition to the former variables). 
# - In 2004 a bidding mechanism was introduced where the model gives a benchmark amount $x$. If an insurer offers a premium below this amount, the insurer keeps 75% of the saving while if the insurer offers a premium above the benchmark, he has to charge the amount above $x$ directly to the insured. 
# What were the objectives of the changes? Make the changes sense?

# 1.1: per period: $(\alpha_l+\lambda\alpha_l+(1-\lambda)\alpha_h)*L/2
# 1.2: low risks would want to switch as other insurers will offer a contract at premium $\alpha_l L<$(\alpha_l+\lambda\alpha_l+(1-\lambda)\alpha_h)*L/2$
# 1.3: show that $p_1^{guaranteed}>p^{const}>p_2^{guaranteed}$; hence budget constraint problems alleviated and better consumption smoothing
# 1.4: per period: $(\alpha_l+\lambda\alpha_m+(1-\lambda)\alpha_h)*L/2; guaranteed renewal premiums: p_1^g=\alpha_l L+(1-\lambda)(\alpha_h-\alpha_m)L and p_2^g=\alpha_m L; note that p^const can be below p_2^g if \alpha_m is large (close to \alpha_h); that is, it is not clear that budget constraints are relaxed more by constant premium 

# 2: ADVANTAGE: much higher prediction power as health care expenditure tend to be serially correlated (even when controlling for various health care conditions); if not doing so health insurers have a highly predictive variable on which they could try to select themselves (e.g. kicking out people with high expenditures int he previous year). DISADVANTAGE: reduced incentives for insurers to cut cost (high expenditure today translates to high payments from risk adjustment scheme next year) --> more waste has to be expected and therfore HCC is generally preferable to expenses; variable not available for new inflow (people from abroad kids etc.). BOTTOM LINE: at the very least, expenditure should not include administrative costs of the insurer, e.g. for claim handling, advertising etc., or costs of bonus benefits (like subsidy for fitness studio etc.)


# E3.1: l=16, h=17
# E3.2: l=11, h= 13 --> higher incentives for selection; take away incentives to not contract high risks
# E3.3: l=11.2, h=9.8 --> incentives for risk selection reversed and bigger than in (a); 
# E3.4: Conditions imply higher expected expenditures for h than for l as $p_l^{10}10+p_l^{30}*30=(p_l^{10}+p_l^{30})10+p_l^{30}*20\leq (p_h^{10}+p_h^{30})10+p_l^{30}*20<(p_h^{10}+p_h^{30})10+p_h^{30}*20=p_h^{10}10+p_h^{30}*30$.  By $p_h^{30}>p_l^{30}$, the subsidies from the fund are higher for a h than for l (while by a similar argument as for expected expenditures in baseline the expenditures are still higher for h than for l) --> lower incentives for risk selection. For the scheme in (c) note that this is a subsidy of 8 for everyone with expenditures greater than 8. As h is more likely to have expenditures above 8, he is more subsidized which reduces incentives for risk selection. More general point: first order stochastic dominance
