#+Title: Exercises
#+AUTHOR:    Christoph Schottmüller
#+Date: 

#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:nil 
#+OPTIONS:   TeX:t LaTeX:t 

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+latex_header: \usepackage{amsmath}\usepackage[margin=2.5cm]{geometry}\usepackage{ae,aecompl}\usepackage{sgame}

* Introduction
1. Assume that the utility function $u_i$ represents $i$'s preferences over a set of alternatives $X=\{x_1,x_2,\dots,x_n\}$. Show that
  1. $i$'s preferences are transitive;
  2. the function $v_i$ defined by $v_i(x)=f(u_i(x))$ also represents $i$'s preferences if $f$ is a strictly increasing function.
  3. Assume now that there are only 2 alternatives, i.e. $X=\{x_1,x_2\}$. Assume that there are 2 people in the society and person 1 prefers $x_1$ over $x_2$ while person 2 prefers $x_2$ over $x_1$. Choose some utility functions $u_1$ and $u_2$ to represent their preferences. Assume that society chooses the alternative $x$ maximizing $u_1(x)+u_2(x)$. 
    - Which alternative does society choose with the utility functions you chose? 
    - Show that a transformation as in the previous subquestion can change society's choice. What is the problem and how does it come about? 

2. Assume that there are $m$ people in society and society has to choose an option from  $X=\{x_1,x_2,\dots,x_n\}$. The preferences of each member of society can be represented by a utility function $u_i$. Society choose the alternative $x\in X$ maximizing $\sum_{i=1}^m u_i(x)$. Show that the chosen alternative is Pareto efficient.

3. Assume $i$'s preferences over lotteries on the set of outcomes $\{healthy,\,ill,\,dead\}$ satisfy the assumptions of the von Neumann-Morgenstern expected utility theorem and can therefore be represented by three numbers $u^{healthy},\,u^{ill}$ and $u^{dead}$. Assume that  $u^{healthy}=1,\,u^{ill}=0.75$ and $u^{dead}=0$.
  1. Treatment 1 leads to the probability distribution over $(0.3,0.5,0.2)$ (over $\{healthy,\,ill,\,dead\}$) while treatment 2 leads to the probability distribution $(0.4,0.3,0.3)$. Which treatment does $i$ prefer?
  2. Show that $i$'s preferences over lotteries can also be represented by the three numbers $v^{healthy}=a*u^{healthy}+b$, $v^{ill}=a*u^{ill}+b$ and $v^{dead}=a*u^{dead}+b$ where $a>0$ and $b\in\Re$ are some real numbers.
  3. Show by means of an example that $i$'s preferences are not necessarily represented by $v^{healthy}=f(u^{healthy})$, $v^{ill}=f(u^{ill})$ and $v^{dead}=f(u^{dead})$ for some strictly increasing function $f$.
* Insurance demand
In all exercises let the person be an expected utility maximizer, i.e. the person's choices satisfy the assumptions of the von Neumann-Morgenstern expected utility theorem.

1. Consider a person with utility of income $u(x)=\sqrt{x}$. Is this person risk averse? For the following lotteries, compute the expected income, the certainty equivalent and the risk premium.
  1. Probability $1/3$ for each $1600$, $2500$, and $3600$ Euros.
  2. Income is uniformly distributed between 1600 and 2500 Euros.

2. Consider a person with utility of income $u(x)=\sqrt{x}$. The person has an income of $2500$ Euros but loses $L$ Euros with probability $\alpha$. Determine the certainty equivalent and the risk premium as a function of $\alpha$ and $L$. Is the risk premium increasing or decreasing in $L$? Is  the risk premium increasing or decreasing in $\alpha$?

3. Consider the utility function $u(x)=-e^{-\eta x}$. The person has an income of $1$ and experiences a loss of $1$ with probability $\alpha$. Is the certainty equivalent in- or decreasing in $\eta$?

4. The Wall Street Journal reported in 2006 of "mini-medical insurance plans". These pland cover routine services, but little hospital coverage and usually have a cap on payouts (say of $ 10.000 ). The premium, however, costs only $ 50 per month. Why might people buy a mini-medical plan? Why are such insurance plans not more popular (in a country where a substatntial part of the population did/does not have health insurance)?  


# E2: \sqrt{CE} = \alpha \sqrt{2500-L}+(1-\alpha) \sqrt{2500}; CE= \alpha^2 (2500-L)+(1-\alpha)^2 2500+\alpha (1-\alpha) \sqrt{(2500-L)2500} = (5000-L) \alpha^2-5000\alpha+2500+(\alpha -\alpha^2) \sqrt{(2500-L)2500};  RP=2500-\alpha L -CE=-\alpha L-(5000-L) \alpha^2+5000\alpha-(\alpha -\alpha^2) \sqrt{(2500-L)2500}
